name       : arp-scan
version    : 1.9.7
release    : 2
source     :
    - https://github.com/royhills/arp-scan/archive/1.9.7.tar.gz : e03c36e4933c655bd0e4a841272554a347cd0136faf42c4a6564059e0761c039
homepage   : https://github.com/royhills/arp-scan
license    : GPL-3.0-or-later
component  : network.util
summary    : The ARP scanner
description: |
    The ARP Scan Tool (AKA ARP Sweep or MAC Scanner) is a very fast ARP packet scanner that shows every active IPv4 device on your subnet.
builddeps  :
    - pkgconfig(libpcap)
rundeps    :
    - libwww-perl
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
